# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

# Methods returning hashes shouldn't be taken care of
Metrics/MethodLength:
  CountAsOne: "hash"